### ISSUE TITLE
Evite nomes de classes, variáveis em Português. Faça sempre em Inglês.

### ISSUE THREAD

**Issue by cheldernunes** [fabrisouza/blog1#1]
https://github.com/fabrisouza/blog1/blob/cb8aa773fe4145ca35144eccbf886525f5883c7d/categorias/models.py#L3

https://github.com/fabrisouza/blog1/blob/master/posts/models.py#L10-L17

e em outras partes do código

**Comment by fabrisouza** [comment]
No caso considero para os proximos projetos, ou já é pra alterar neste?

**Comment by cheldernunes** [comment]
> No caso considero para os proximos projetos, ou já é pra alterar neste?

Vamos deixar para os próximos projetos. Não precisa alterar neste
